### ISSUE TITLE
Preprocessing steps

### ISSUE THREAD

**Issue by hasam6400** [Mawiszus/World-GAN#2]
Hi, 
Can you please explain about the data and the preprocessing steps as well as code for it? I am trying to use my own data.
You response would be very helpful for me.
Thank you

**Comment by Mawiszus** [comment]
Hi Hasam,
this code uses [PyAnvilEditor](https://github.com/DonoA/PyAnvilEditor) as a submodule to read minecraft world files and then converts them to torch tensors. You can find the relevant code in [level_utils.py](https://github.com/Mawiszus/World-GAN/blob/main/minecraft/level_utils.py#L172). If you want to train with your own 3D Data, you need to provide it as a torch tensor in a similar shape as calculated here. I would suggest writing your own `read_level` function and calling that instead of  `read_level_from_file` [here](https://github.com/Mawiszus/World-GAN/blob/main/minecraft/level_utils.py#L157).
Hope this helps,
Maren
